# Generated by Django 4.0.1 on 2022-01-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='returntooffice',
            name='additionalPart',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='comments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='fullyEquipedMonitor',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='fullyEquipedMonitorPercent',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='geography',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='managerResponsible',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='meaws',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='missingParts',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='mr',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='numberOfDesk',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='targetToFullyequipPercent',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='returntooffice',
            name='toMr',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='returntooffice',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
