# Generated by Django 4.0.1 on 2022-01-15 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_returntooffice_additionalpart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntooffice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
