# Generated by Django 4.0.1 on 2022-03-01 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_returntooffice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('site', models.CharField(default='', max_length=30)),
                ('sitelead', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('sitedelegate', models.CharField(default='', max_length=150)),
                ('facilitieslead', models.CharField(default='', max_length=150)),
                ('securitylead', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
